### ISSUE TITLE
Have/use symbols also for pronouns (and preverbs)

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#489]
Following up on #358, we should add symbols for animate and inanimate pronouns:

> PrA: ➡️🧑🏽 or  →🧑🏽
> PrI: ➡️💧 or →💧

Likewise, preverbs should use the lightning symbol, as a subcategory of particles, similar to what is already the case for e.g. prenouns (cf. [amisko-](https://sapir.artsrn.ualberta.ca/cree-dictionary/word/amisko-/)).

These have already been added `crk.altlab.tsv`.

I suppose the arrow might be different from that used in verbs, if we want more differentiation.

**Comment by aarppe** [comment]
@eddieantonio I presume this could be for you? Or would we have some particular reason why pronouns don't get a symbol (nor preverbs)?

**Comment by eddieantonio** [comment]
> @eddieantonio I presume this could be for you? Or would we have some particular reason why pronouns don't get a symbol (nor preverbs)?

Yes, this is a bug. I would assume that these should automatically get the symbol when you added them to `crk.altlabel.tsv`...

**Comment by aarppe** [comment]
> I would assume that these should automatically get the symbol when you added them to crk.altlabel.tsv

That is what I assumed as well.

**Comment by eddieantonio** [comment]
So the reason this isn't currently matching is because the emoji labels match based on the wordclass of the _analysis_.

Consider "niya":

```sh
$ echo "niya" | hfst-optimized-lookup crk-strict-analyzer.hfstol
niya	niya+Pron+Pers+1Sg
```

It's a `+Pron+Pers+1Sg`, but the label is for `PrA`.

I don't know if this is an issue with the FST, or with the dictionary, or with the altlabel file. I can make it work with some hacky code, but I'd rather understand what is the most correct solution before commiting to anything. Thoughts @aarppe?

**Comment by aarppe** [comment]
I would avoid too hacky/Cree-specific solutions.

One way to deal with this is go with the current logic, i.e. have an emoji for `+Pron`, which would be: → (or ➡️). I tried to make that change, but got an [error message](https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/actions/runs/159634550).

How personal pronouns are coded would suggest that one could use a feature sequence for a more precise symbol, i.e. `+Pron+Pers` for →🧑🏽. Does the current algorithm prioritize feature sequences over individual features? However, this becomes more difficult for demonstrative pronouns, where the animacy is close to the end of the feature sequence, e.g. `ôma+Pron+Dem+Prox+I+Sg`. Of course, if feature sequences are used, then one could just enumerate all such sequences, e.g. `Pron+Dem+Prox+I` etc., to get →💧 . 

Anyhow, the original logic was that the `(i)` button presents the results of the linguistic analysis, for the inflected word form, and the emoji/symbol line presents lexical information from the dictionary source, for the lemma/dictionary entry. Also, the original thought was that the lexical information is divided into 1) the specific wordclass (emoji/symbol) and 2) the inflectional subcategory. Of course, the linguistic analysis does also contain the specific wordclass, though often represented by a feature pair. Again, does the specification of emojis/symbols allow for multi-feature sequences? The inflectional subcategory as found in the CW source also includes both types of information, in that one can strip the inflectional subcategory (`-[number/character]`). But I'd almost rather consider doing this explicitly `in crk.altlabel.tsv`, perhaps adding a column, if we'd be fetching this information from there.

Another matter is that if we want to allow for the optionality of getting linguistic terms rather than emojis/symbols, `V+TA` -> `Verb Transitive Animate` or `N+A+D` -> `Noun Animate Dependent` becomes just prohibitively long to show, in which case we had previously decided to show just the general wordclass (with the specific word-class presented implicitly by the rendering of the inflectional category by example words). There does not appear to be a clean way to do this, unless we'd revise the FST so that e.g. `VTA` is the wordclass, rather than `V` with a subtype of `TA`. Or, we include more coding schemes in `crk.altlabel.tsv` - this latter solution would be my preference.

**Comment by aarppe** [comment]
Forgot to note, how are preverbs treated, in contrast to e.g. prenouns? Preverbs are not full inflected wordforms, so they wouldn't be recognized by the normative FST, though the new descriptive FST has been modified to also provide analyses for fragments, in effect any combination of prefix sequences without the stem and suffixes, and also the stem part by itself.

But now, _amisko-_ gets a lighting for being a particle plus the like-exemplar, but _miyo-_ only gets the like-exemplar but not the lightning? All types of particles should be treated similarly, and my preference is what has currently been implemented for prenouns, i.e. symbol/emoji + like-exemplar.

**Comment by eddieantonio** [comment]
> I tried to make that change, but got an [error message](https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/actions/runs/159634550).

That error was due to an unrelated issue; it should hopefully be resolved now.

**Comment by aarppe** [comment]
Ok - but the arrow is still not appearing as an emoji → for pronouns.

**Comment by eddieantonio** [comment]
> Ok - but the arrow is still not appearing as an emoji → for pronouns.

Haha, I meant for _that_ particular issue. There is an additional complication in that, internally, the wordclass of "niya" is `Pron`. Just `Pron`. I still need to investigate the other preverbs.

> How personal pronouns are coded would suggest that one could use a feature sequence for a more precise symbol, i.e. +Pron+Pers for →🧑🏽. Does the current algorithm prioritize feature sequences over individual features? 

Yes, it prioritizes longest sequences.

---

I will mull over the other thoughts in this thread tomorrow!

**Comment by aarppe** [comment]
Right now, to resolve pronouns, I'd just have `+Pron` point to → in `crk.altlabel.tsv`. If we relabel longer sequences with symbols/emojis, that may have unexpected consequences for the relabeling of these feature sequences in the linguistic analyses - something we don't necessarily want. Though I find `+Pron+Pers` -> `Pointing word + Person` more informative than`Pointing word - like: niya`, the latter could work - but `Pron+Dem+Prox+I `for `Pointing word - like: ôma` would have us lose the information on the _proximacy vs. distalcy_.

But what would need to be dealt with is how preverbs get coded, as they shouldn't receive a proper linguistic analysis.

**Comment by aarppe** [comment]
Excellent! - now all dictionary entries get a symbolic representation.
